name: major_project
description: "A mobile-based civic issue reporting system."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Added for Civic Issue Reporting features
  image_picker: ^1.0.7        # To capture/pick photos
  geolocator: ^10.1.0         # To get GPS coordinates
  http: ^1.2.0                # To connect to Node.js backend
  intl: ^0.19.0               # For date/time formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # If you plan to add a logo or custom icons later, uncomment this:
  # assets:
  #   - assets/images/